import { Router } from "express";
import { createBooking, getBookings, updateBookingStatus, verifySessionCode, submitReview, getTutorReviews } from "../controllers/booking.controller.js";
import { protect, authorize } from "../middleware/auth.middleware.js";
import { ROLES } from "../utils/constants.js";
const router = Router();
router.post("/", protect, authorize(ROLES.STUDENT), createBooking);
router.get("/", protect, getBookings);
router.patch("/:id/status", protect, authorize(ROLES.TUTOR, ROLES.ADMIN), updateBookingStatus);
router.post("/:id/verify-code", protect, authorize(ROLES.TUTOR), verifySessionCode);
router.post("/:id/review", protect, authorize(ROLES.STUDENT), submitReview);
router.get("/tutor/:tutorId/reviews", getTutorReviews);
export default router;
